import type { Metadata } from "next";
import { Geist, Geist_Mono , Michroma } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastifyProvider";
import { SiteDrawer } from "@/components/SiteDrawer";
 
import FooterWrapper from "@/components/FooterWrapper";
import HeaderWrapper from "@/components/HeaderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${michroma.className} antialiased`}>
        <div>

          <HeaderWrapper/>
      
        </div>
        <ToastProvider />
        {children}
          <FooterWrapper />
       </body>
    </html>
  );
}
